/**
 * Embeds the built SPA (dashboard/dist) into a TypeScript module so the
 * server can be compiled to a single standalone executable with
 * `bun build --compile` - users install HBS with no runtime, no Bun, no Node.
 *
 * `bun run build` runs this right after `vite build`. The generated file is
 * gitignored: repo checkouts fall back to serving dist/ from disk, and dev
 * runs use Vite anyway.
 *
 *   bun run tools/embed-dist.ts
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

const root = dirname(import.meta.dir);
const distDir = join(root, "dist");
const outFile = join(root, "server", "dist.embedded.generated.ts");

if (!statSync(distDir, { throwIfNoEntry: false })?.isDirectory()) {
  console.error(`embed-dist: ${distDir} does not exist - run \`vite build\` first`);
  process.exit(1);
}

const files: string[] = [];
(function walk(dir: string) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(full);
  }
})(distDir);

const entries = files
  .map((full) => {
    const key = relative(distDir, full).split(sep).join("/");
    const b64 = readFileSync(full).toString("base64");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(b64)},`;
  })
  .sort()
  .join("\n");

const banner = `// @generated by tools/embed-dist.ts - do not edit.
// Base64 map of the built SPA, embedded in \`bun build --compile\` standalone
// server binaries. Absent keys fall back to serving dashboard/dist from disk.
`;

writeFileSync(
  outFile,
  `${banner}export const EMBEDDED_DIST: Record<string, string> = {\n${entries}\n};\n`,
);
console.log(`embed-dist: embedded ${files.length} files into ${relative(root, outFile)}`);
